on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: python -m pip install --quiet poetry==1.*
    - run: poetry install
    - run: poetry run python ./scripts/check.py
    - run: poetry run python -m aoc2023.main
